In [42]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np        

In [43]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [44]:
dataset=pd.get_dummies(dataset,drop_first=True)
dataset

age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [45]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [46]:
ind=dataset[['age', 'bmi', 'children','sex_male','smoker_yes']]
ind

age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [47]:
dep=dataset[['charges']]
dep

charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [48]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(ind,dep,test_size=0.30,random_state=0)

In [49]:

from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [50]:
preinput=sc.transform(([[1234,345,4565,1,0,]]))

C:\Users\ragus\HOPES\ANACONDA 3\lib\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  "X does not have valid feature names, but"


In [51]:
preinput

array([[ 8.52925260e+01,  5.04227773e+01,  3.79204397e+03,
         1.02378711e+00, -5.04669881e-01]])

In [52]:
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVR
param_grid={"kernel":["rbf","sigmoid","linear","poly"],"C":[10,200,300,1000,3000],"gamma":["auto","scale"]}
grid=GridSearchCV(SVR(),param_grid,refit=True,verbose=3,n_jobs=-1)
grid.fit(x_train,y_train)
re=grid.cv_results_
print("the best parameters of tuning{}:".format(grid.best_params_))

Fitting 5 folds for each of 40 candidates, totalling 200 fits


C:\Users\ragus\HOPES\ANACONDA 3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


the best parameters of tuning{'C': 3000, 'gamma': 'scale', 'kernel': 'poly'}:


In [53]:

table=pd.DataFrame.from_dict(re)
table

mean_fit_time  std_fit_time  mean_score_time  std_score_time param_C  \
0        0.105429      0.007272         0.040947        0.001984      10   
1        0.118734      0.005264         0.018257        0.004605      10   
2        0.073938      0.006222         0.021056        0.007329      10   
3        0.076083      0.003415         0.018003        0.003136      10   
4        0.110385      0.009845         0.054938        0.018836      10   
5        0.114337      0.021322         0.018429        0.006439      10   
6        0.070640      0.007246         0.015645        0.000002      10   
7        0.075419      0.006249         0.018792        0.006811      10   
8        0.098995      0.006112         0.045688        0.002778     200   
9        0.108047      0.004288         0.022223        0.006385     200   
10       0.096485      0.011239         0.015452        0.000774     200   
11       0.090344      0.006408         0.016402        0.001556     200   
12       0.104294      0.007391         0.046250        0.001558     200   
13       0.112564      0.012454         0.018815        0.006365     200   
14       0.103806      0.021972         0.015340        0.008829     200   
15       0.103359      0.018435         0.018751        0.006251     200   
16       0.103306      0.007655         0.050891        0.006855     300   
17       0.121866      0.029999         0.017336        0.007553     300   
18       0.100026      0.012726         0.015715        0.000156     300   
19       0.103716      0.005520         0.016260        0.006066     300   
20       0.112913      0.007227         0.046757        0.003708     300   
21       0.130909      0.022751         0.022554        0.006480     300   
22       0.111967      0.012650         0.015958        0.002324     300   
23       0.113597      0.014837         0.019806        0.003379     300   
24       0.137417      0.010334         0.052930        0.005858    1000   
25       0.131801      0.006479         0.027636        0.005220    1000   
26       0.118156      0.007113         0.014430        0.002459    1000   
27       0.127855      0.023162         0.015635        0.000009    1000   
28       0.126397      0.016169         0.055586        0.007294    1000   
29       0.131374      0.007619         0.029275        0.005484    1000   
30       0.129654      0.003168         0.016421        0.002640    1000   
31       0.139616      0.024701         0.018944        0.001814    1000   
32       0.155524      0.016543         0.048433        0.001029    3000   
33       0.129737      0.012999         0.025187        0.007440    3000   
34       0.155995      0.009755         0.015632        0.000004    3000   
35       0.298314      0.114618         0.016424        0.004885    3000   
36       0.161271      0.017466         0.054502        0.004741    3000   
37       0.139662      0.009315         0.022556        0.002685    3000   
38       0.162121      0.007246         0.013730        0.000999    3000   
39       0.240970      0.067147         0.014988        0.004839    3000   

   param_gamma param_kernel  \
0         auto          rbf   
1         auto      sigmoid   
2         auto       linear   
3         auto         poly   
4        scale          rbf   
5        scale      sigmoid   
6        scale       linear   
7        scale         poly   
8         auto          rbf   
9         auto      sigmoid   
10        auto       linear   
11        auto         poly   
12       scale          rbf   
13       scale      sigmoid   
14       scale       linear   
15       scale         poly   
16        auto          rbf   
17        auto      sigmoid   
18        auto       linear   
19        auto         poly   
20       scale          rbf   
21       scale      sigmoid   
22       scale       linear   
23       scale         poly   
24        auto          rbf   
25        auto      sigmoid   
26        auto       linear   
27        auto     

In [54]:
from sklearn.svm import SVR
regressor=SVR(kernel="rbf",C=1000)
regressor.fit(x_train,y_train)

C:\Users\ragus\HOPES\ANACONDA 3\lib\site-packages\sklearn\utils\validation.py:993: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


SVR(C=1000)

In [55]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:23
BMI:36
Children:1
Sex Male 0 or 1:0
Smoker Yes 0 or 1:1


In [56]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[-122319.73774343]


In [57]:
regressor.intercept_

array([14948.96194087])

In [58]:
regressor.n_support_

array([936])

In [59]:
regressor.support_

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [60]:
y_pred=regressor.predict(x_test)

In [61]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [62]:
r_score

0.8102064851758545

In [63]:
import pickle
filename="finalized_svm.sav"
pickle.dump(regressor,open(filename,"wb"))
loaded_model=pickle.load(open("finalized_svm.sav","rb"))

In [64]:
result=loaded_model.predict([[1234,345,4565,1,0]])

In [65]:
result

array([14948.96194087])

In [66]:
preoutput=sc.transform(([[1234,345,4565,1,0]]))

In [67]:
preoutput

array([[ 8.52925260e+01,  5.04227773e+01,  3.79204397e+03,
         1.02378711e+00, -5.04669881e-01]])